import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function logined() {
  return (
    <>
      <Head>
        <title>App | title</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link
          href="/map"
          style={{
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
            width: '100%',
            height: '100vh',
            textDecoration: 'none',
          }}
        >
        <Image
          width={350}
          height={100}
          alt="back"
          src={"/common/logo2.svg"}
          style={{
            display: 'flex',
            alignItems: "center",
            justifyContent: "center",
            marginBottom: '150px',
            color: 'white',
          }}
        />
          <div
            style={{
              display: 'flex',
              justifyContent: 'center',
              alignItems: 'center',
              width: '70%',
              height: '55px',
              border: 'none',
              color: "black",
              fontWeight: 'bold',
              marginBottom: '2rem',
            }}
          >
            スタートボタン
          </div>
        </Link>
      </main>
    </>
  );
}
