import Head from "next/head";

export default function logined() {
  return (
    <>
      <Head>
        <title>App | title</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          style={{
            backgroundColor: "#999",
            position: "absolute",
            top: 100,
            left: "40%",
            width: 100,
            height: 100,
          }}
        >
          ロゴ
        </div>
        <a
          style={{
            backgroundColor: "white",
            color: "black",
            border: "1px solid black",
            position: "absolute",
            bottom: 300,
            left: "40%",
          }}
          href="/"
        >
          スタートボタン
        </a>
      </main>
    </>
  );
}
