import Head from "next/head";

export default function Login() {

  return (
    <>
      <Head>
        <title>App | Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          style={{
            backgroundColor: "#999",
            position: "absolute",
            top: 100,
            left: "40%",
            width: 100,
            height: 100,
          }}
        >
          ロゴ
        </div>
        <input
          value=""
          placeholder="ユーザーネーム"
          style={{
            backgroundColor: "white",
            color: "black",
            border: "1px solid black",
            position: "absolute",
            bottom: 300,
            left: "30%",
          }}
        />
        <input
          value=""
          placeholder="メールアドレス"
          style={{
            backgroundColor: "white",
            color: "black",
            border: "1px solid black",
            position: "absolute",
            bottom: 250,
            left: "30%",
          }}
        />
        <input
          value=""
          placeholder="パスワード"
          style={{
            backgroundColor: "white",
            color: "black",
            border: "1px solid black",
            position: "absolute",
            bottom: 200,
            left: "30%",
          }}
        />

        <button
          style={{
            backgroundColor: "black",
            color: "white",
            border: "1px solid black",
            position: "absolute",
            bottom: 150,
            left: "15%",
          }}
        >
          新規登録
        </button>
        <a
          style={{
            backgroundColor: "white",
            color: "black",
            border: "1px solid black",
            position: "absolute",
            bottom: 150,
            right: "15%",
          }}
          href="/login/logined"
        >
          ログイン
        </a>
      </main>
    </>
  );
}
