import Head from "next/head"
import React, { useState } from 'react'
import Image from "next/image"
import { Inter } from "next/font/google"
import { useRecoilState } from 'recoil'
import { modalState } from '../../atoms/modalAtom'
import TitleModal from '../components/title/TitleModal'

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [showModal , setShowModal] = useRecoilState(modalState)
  const [loginModal, setLoginModal] = useState(false)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
            width: '100%',
            height: '100vh',
          }}
        >
        <Image
          width={100}
          height={100}
          alt="back"
          src={"/common/logo.svg"}
          style={{
            display: 'flex',
            alignItems: "center",
            justifyContent: "center",
            marginBottom: '150px',
            borderRadius: '100%',
            color: 'white',
          }}
        />
          <button
            style={{
              display: 'flex',
              justifyContent: 'center',
              alignItems: 'center',
              backgroundColor: "#0098FD",
              width: '70%',
              height: '55px',
              borderRadius: '30px',
              border: 'none',
              color: "white",
              marginBottom: '2rem',
            }}
            onClick={()=>{
              setLoginModal(false)
              setShowModal(true)
            }}
          >
            新規登録
          </button>
          <button
            style={{
              display: 'flex',
              justifyContent: 'center',
              alignItems: 'center',
              backgroundColor: "#e0e0e0",
              width: '70%',
              height: '55px',
              borderRadius: '30px',
              border: 'none',
              color: "#0098FD",
              marginBottom: '2rem',
            }}
            onClick={()=>{
              setLoginModal(true)
              setShowModal(true)
            }}
          >
            ログイン
          </button>

          {/* モーダル表示 */}
          {
            showModal && <TitleModal props={loginModal} />
          }
        </div>
      </main>
    </>
  );
}
