import Head from "next/head";
import { ButtonNav } from "@/components/ButtonNav";
import { GoogleMap, LoadScriptNext } from "@react-google-maps/api";
import { useEffect, useState } from "react";

export default function map() {
  // 現在位置
  const [center, setCenter] = useState({ lat: 0, lng: 0 });

  // 現在位置を取得
  useEffect(() => {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition((position) => {
        setCenter({
          lat: position.coords.latitude,
          lng: position.coords.longitude,
        });
      });
    }
  }, []);

  return (
    <>
      <Head>
        <title>App | title</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <LoadScriptNext googleMapsApiKey="">
          <GoogleMap
            mapContainerStyle={{
              width: "100%",
              height: "100vh",
            }}
            center={center}
            zoom={15}
            clickableIcons={false}
            options={{
              gestureHandling: "greedy",
              streetViewControl: false,
              fullscreenControl: false,
              disableDefaultUI: false,
              mapTypeControl: false,
              zoomControl: false,
            }}
          ></GoogleMap>
        </LoadScriptNext>
        <ButtonNav />
      </main>
    </>
  );
}
