import Head from 'next/head'
import { ButtonNav } from '@/components/ButtonNav'

export default function map() {
  return (
    <>
      <Head>
        <title>App | title</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>マップ画面</div>
        <ButtonNav />
      </main>
    </>
  )
}