import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { ButtonNav } from "@/components/ButtonNav";

const inter = Inter({ subsets: ["latin"] });

export default function Submit() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          style={{
            position: "absolute",
            bottom: -50,
            left: 0,
            width: "100%",
            height: 800,
            borderRadius: 50,
            boxShadow: "0px 0px 10px 10px #999",
          }}
        >
          <dl
            style={{
              marginTop: 50,
            }}
          >
            <dt>タイトル</dt>
            <dd>
              <input type="text" name="title" value={"タグ名"} />
            </dd>
          </dl>

          <dl
            style={{
              marginTop: 100,
            }}
          >
            <dt>内容</dt>
            <dd>
              <input type="text" name="title" value={"テキスト"} />
            </dd>
          </dl>

          <dl
            style={{
              marginTop: 50,
            }}
          >
            <dt>マークカラー</dt>
            <dd>
              <div
                style={{
                  width: 50,
                  height: 50,
                  borderRadius: "50%",
                  backgroundColor: "red",
                }}
              >
                いろ
              </div>
            </dd>
          </dl>
        </div>
      </main>
    </>
  );
}
